name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        PAT: ${{ secrets.PAT }}
      run: | 
        docker login ghcr.io -u ranapushpender -p $PAT
        TAG=`git rev-parse --short HEAD`
        docker build . --file Dockerfile --tag ghcr.io/ranapushpender/rdesktop-wine/rdesktop-wine:$TAG --tag ghcr.io/ranapushpender/rdesktop-wine/rdesktop-wine:latest
        docker push ghcr.io/ranapushpender/rdesktop-wine/rdesktop-wine:$TAG
        docker push ghcr.io/ranapushpender/rdesktop-wine/rdesktop-wine:latest
